title: 小槌.net

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: jekyll-whiteglass
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
